pool:
  vmImage: 'ubuntu-latest'

name: $(BuildID)-$(Build.SourceBranchName)

stages:
- stage: build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - job: packProxy
      displayName: Pack docker image
      steps:
        - task: Docker@2
          displayName: buildAndPush
          inputs:
            containerRegistry: 'rtuitlab connection by admin'
            repository: 'rtuitlab/sber-realityshift-proxy'
            command: 'buildAndPush'
            Dockerfile: './Proxy/Dockerfile'
            buildContext: './Proxy'
            tags: |
              $(Build.BuildId)
              latest