version: '3.8'

services:
    api:
      image: rtuitlab/sber-realityshift-api
      deploy:
        resources:
          limits:
            cpus: '0.10'
            memory: 200M
          reservations:
            cpus: '0.05'
            memory: 20M
      logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"
    front:
      image: rtuitlab/sber-realityshift-front
      deploy:
        resources:
          limits:
            cpus: '0.10'
            memory: 50M
          reservations:
            cpus: '0.05'
            memory: 20M
      logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"
    proxy:
      image: rtuitlab/sber-realityshift-proxy
      deploy:
        resources:
          limits:
            cpus: '0.10'
            memory: 50M
          reservations:
            cpus: '0.05'
            memory: 20M
      logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"